apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  minReadySeconds: 10
  replicas: 10
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: wdalmut/app1:15
        name: hello-pod
        ports:
        - containerPort: 3000
