apiVersion: v1
kind: Service
metadata:
  name: hello-svc
  namespace: quality
  labels:
    app: hello
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 31001
      protocol: TCP
  selector:
    app: hello

